import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-home-health-evv-claims-recovery",
  "engine": "recovery",
  "title": "Home Health EVV & Claims Recovery",
  "shortTitle": "Home Health EVV and Claims Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through home health evv & claims recovery",
  "industry": "Home Health Revenue Integrity",
  "uiPort": 4594,
  "apiPort": 5594,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Home Health EVV & Claims Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidAmount",
    "expectedKey": "expectedAmount",
    "actualLabel": "Payer Paid Amount",
    "expectedLabel": "Supported Episode Reimbursement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Home Health EVV & Claims Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("patient-episode-registry","HHE01","Patient episode registry","Execute patient episode registry using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed patient episode registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","Patient episode registry Reference","text","HHE01-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("plan-of-care-tracking","HHE02","Plan-of-care tracking","Execute plan-of-care tracking using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed plan-of-care tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","Plan-of-care tracking Reference","text","HHE02-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("order-and-signature-control","HHE03","Order and signature control","Execute order and signature control using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed order and signature control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","Order and signature control Reference","text","HHE03-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("face-to-face-validation","HHE04","Face-to-face validation","Execute face-to-face validation using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed face-to-face validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","Face-to-face validation Reference","text","HHE04-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("evv-event-ingestion","HHE05","EVV event ingestion","Execute evv event ingestion using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed evv event ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","EVV event ingestion Reference","text","HHE05-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("scheduled-versus-delivered-visits","HHE06","Scheduled versus delivered visits","Execute scheduled versus delivered visits using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed scheduled versus delivered visits decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","Scheduled versus delivered visits Reference","text","HHE06-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("missing-check-in-remediation","HHE07","Missing check-in remediation","Execute missing check-in remediation using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed missing check-in remediation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","Missing check-in remediation Reference","text","HHE07-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("oasis-validation","HHE08","OASIS validation","Execute oasis validation using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed oasis validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","OASIS validation Reference","text","HHE08-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("pdgm-grouping-reconstruction","HHE09","PDGM grouping reconstruction","Execute pdgm grouping reconstruction using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed pdgm grouping reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","PDGM grouping reconstruction Reference","text","HHE09-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("lupa-threshold-monitoring","HHE10","LUPA threshold monitoring","Execute lupa threshold monitoring using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed lupa threshold monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","LUPA threshold monitoring Reference","text","HHE10-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("comorbidity-adjustment-validation","HHE11","Comorbidity adjustment validation","Execute comorbidity adjustment validation using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed comorbidity adjustment validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","Comorbidity adjustment validation Reference","text","HHE11-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("claim-generation-and-scrub","HHE12","Claim generation and scrub","Execute claim generation and scrub using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed claim generation and scrub decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","Claim generation and scrub Reference","text","HHE12-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("denial-classification","HHE13","Denial classification","Execute denial classification using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed denial classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","Denial classification Reference","text","HHE13-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("appeal-package-generation","HHE14","Appeal package generation","Execute appeal package generation using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed appeal package generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","Appeal package generation Reference","text","HHE14-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]}),
feature("episode-profitability-analytics","HHE15","Episode profitability analytics","Execute episode profitability analytics using patient episodes, plans of care, physician orders, face-to-face encounters, EVV events, scheduled visits, OASIS, PDGM groupings, claims, denials, and remittances.","Produce a governed episode profitability analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Agency / Patient Episode","text","Agency / Patient Episode · Standard Case"],["caseReference","Episode profitability analytics Reference","text","HHE15-2026-001"],["paidAmount","Payer Paid Amount","currency",475500],["expectedAmount","Supported Episode Reimbursement","currency",561090],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Patient episode registry case","Plan-of-care tracking case","Order and signature control case","Face-to-face validation case","EVV event ingestion case"]})
]);
